apiVersion: apps/v1
kind: Deployment
metadata:
  name: couponapi
  labels:
    app: couponapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: couponapi
  template:
    metadata:
      labels:
        app: couponapi
    spec:
      containers:
      - name: couponapi
        image: containerimagebuild.azurecr.io/infyshopcouponapi
        ports:
        - containerPort: 80
        env:
          - name: IdentityServerAuthority
            value: http://identityserver-service
          - name: ConnectionStrings__CouponConnectionString
            value: Server=mssqldb-service,1433;Database=InfyCouponAPI;Trusted_Connection=false;MultipleActiveResultSets=true;User Id=sa;Password=MyC0m9l&xP@ssw0rd

---

apiVersion: v1
kind: Service
metadata:
  name: couponapi-service
spec:
  type: LoadBalancer #can be commented to keep it as a cluster ip and not publicly exposed
  selector:
    app: couponapi
  ports:
    - port: 80