apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver
  labels:
    app: identityserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityserver
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
      - name: identityserver
        image: containerimagebuild.azurecr.io/infyshopidentity
        ports:
        - containerPort: 80
        env:
          - name: RedirectUris
            value: http://52.190.29.35/signin-oidc
          - name: PostLogoutRedirectUris
            value: http://52.190.29.35/signout-callback-oidc
          - name: ConnectionStrings__IdentityServerConnectionString
            value: Server=mssqldb-service,1433;Database=InfyIdentityServer;Trusted_Connection=false;MultipleActiveResultSets=true;User Id=sa;Password=MyC0m9l&xP@ssw0rd

---

apiVersion: v1
kind: Service
metadata:
  name: identityserver-service
spec:
  type: LoadBalancer
  selector:
    app: identityserver
  ports:
    - port: 80