apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi
  labels:
    app: orderapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi
        image: containerimagebuild.azurecr.io/infyshoporderapi
        ports:
        - containerPort: 80
        env:
          - name: IdentityServerAuthority
            value: http://identityserver-service
          - name: ConnectionStrings__OrderConnectionString
            value: Server=mssqldb-service,1433;Database=InfyOrderAPI;Trusted_Connection=false;MultipleActiveResultSets=true;User Id=sa;Password=MyC0m9l&xP@ssw0rd
          - name: ServiceBusConnectionString
            value: Endpoint=sb://cleanarchservicebusns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=nFDVtKD2VQIp+PnQRzbS+tcaX6wVs8iOHANsav/DpEM=

---