apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentapi
  labels:
    app: paymentapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentapi
  template:
    metadata:
      labels:
        app: paymentapi
    spec:
      containers:
      - name: paymentapi
        image: containerimagebuild.azurecr.io/infyshoppaymentapi
        ports:
        - containerPort: 80
        env:
          - name: ServiceBusConnectionString
            value: Endpoint=sb://cleanarchservicebusns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=nFDVtKD2VQIp+PnQRzbS+tcaX6wVs8iOHANsav/DpEM=

---

apiVersion: v1
kind: Service
metadata:
  name: paymentapi-service
spec:
#  type: LoadBalancer
  selector:
    app: paymentapi
  ports:
    - port: 80