apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi
  labels:
    app: productapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
    spec:
      containers:
      - name: productapi
        image: containerimagebuild.azurecr.io/infyshopproductapi
        ports:
        - containerPort: 80
        env:
          - name: IdentityServerAuthority
            value: http://identityserver-service
          - name: ConnectionStrings__ProductConnectionString
            value: Server=mssqldb-service,1433;Database=InfyProductAPI;Trusted_Connection=false;MultipleActiveResultSets=true;User Id=sa;Password=MyC0m9l&xP@ssw0rd

---

apiVersion: v1
kind: Service
metadata:
  name: productapi-service
spec:
  type: LoadBalancer
  selector:
    app: productapi
  ports:
    - port: 80