apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfrontend
  labels:
    app: webfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webfrontend
  template:
    metadata:
      labels:
        app: webfrontend
    spec:
      containers:
      - name: webfrontend
        image: containerimagebuild.azurecr.io/infshopweb
        ports:
        - containerPort: 80
        env:
          - name: ServiceUrls__IdentityAPI
            value: http://13.91.125.217
          - name: ServiceUrls__ProductAPI
            value: http://apigateway-service
          - name: ServiceUrls__ShoppingCartAPI
            value: http://apigateway-service
          - name: ServiceUrls__CouponAPI
            value: http://apigateway-service

---

apiVersion: v1
kind: Service
metadata:
  name: webfrontend-service
spec:
  type: LoadBalancer
  selector:
    app: webfrontend
  ports:
    - port: 80