version: '3.4'

services:
  infyshop.couponapi:
    container_name: infyshopcouponapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CouponConnectionString=Server=tcp:infyshopserver.database.windows.net,1433;Initial Catalog=InfyShopDB;Persist Security Info=False;User ID=admin1;Password=N1ger1a!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "IdentityServerAuthority=http://infyshopidentity.eastus.azurecontainer.io/"

  infyshop.orderapi:
    container_name: infyshoporderapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnectionString=Server=tcp:infyshopserver.database.windows.net,1433;Initial Catalog=InfyShopDB;Persist Security Info=False;User ID=admin1;Password=N1ger1a!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "IdentityServerAuthority=http://infyshopidentity.eastus.azurecontainer.io/"

  infyshop.paymentapi:
    container_name: infyshoppaymentapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  infyshop.productapi:
    container_name: infyshopproductapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ProductConnectionString=Server=tcp:infyshopserver.database.windows.net,1433;Initial Catalog=InfyShopDB;Persist Security Info=False;User ID=admin1;Password=N1ger1a!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - "IdentityServerAuthority=http://infyshopidentity.eastus.azurecontainer.io/"
