apiVersion : apps/v1
kind: Deployment
metadata:
  name: infshopweb 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infshopweb
  template:
    metadata:
      labels:
        app: infshopweb 
    spec:
      containers:
        - name: infshopweb 
          image: containerimagebuild.azurecr.io/infshopweb
          ports:
          - containerPort: 80