# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
    branches:
        include:
        - master
    paths:
        include:
        - AzureKubernetes/mssql.yml

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '65baa412-40b1-4d0d-b59c-6db7e9b71530'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'containerimagebuild370945a4-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Deploy
  displayName: Deploy MSSQL

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'lateef10InfyShopMicroservice-2017.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo "Listing files in the current directory..."
                ls -al
              workingDirectory: '$(Pipeline.Workspace)'
          - task: CopyFiles@2
            inputs:
              SourceFolder: 'AzureKubernetes'
              Contents: 'mssql.yml'
              TargetFolder: '$(Pipeline.Workspace)'
              OverWrite: true
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'infycluster-default-1216'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: '$(Pipeline.Workspace)/mssql.yml'




