apiVersion: apps/v1
kind: Deployment
metadata:
  name: couponapi
  labels:
    app: couponapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couponapi
  template:
    metadata:
      labels:
        app: couponapi
    spec:
      containers:
      - name: couponapi
        image: infyshopcouponapi
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: IdentityServerAuthority
            value: http://identityserver-service
          - name: ConnectionStrings__CouponConnectionString
            value: Server=mssqldb-service,1433;Database=InfyCouponAPI;Trusted_Connection=false;MultipleActiveResultSets=true;User Id=sa;Password=MyC0m9l&xP@ssw0rd

---

apiVersion: v1
kind: Service
metadata:
  name: couponapi-service
spec:
  type: NodePort
  selector:
    app: couponapi
  ports:
    - port: 80