apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver
  labels:
    app: identityserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityserver
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
      - name: identityserver
        image: infyshopidentity
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: environmentVariables__ASPNETCORE_ENVIRONMENT
            value: Development
          - name: RedirectUris
            value: http://webfrontend-service/signin-oidc
          - name: PostLogoutRedirectUris
            value: http://webfrontend-service/signout-callback-oidc
          - name: ConnectionStrings__IdentityServerConnectionString
            value: Server=mssqldb-service,1433;Database=InfyIdentityServer;Trusted_Connection=false;MultipleActiveResultSets=true;User Id=sa;Password=MyC0m9l&xP@ssw0rd

---

apiVersion: v1
kind: Service
metadata:
  name: identityserver-service
spec:
  type: NodePort
  selector:
    app: identityserver
  ports:
    - port: 80