apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcartapi
  labels:
    app: shoppingcartapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingcartapi
  template:
    metadata:
      labels:
        app: shoppingcartapi
    spec:
      containers:
      - name: shoppingcartapi
        image: infyshopshoppingcartapi
        ports:
        - containerPort: 80
        env:
          - name: IdentityServerAuthority
            value: https://identityserver-service
          - name: ServiceUrls__CouponAPI
            value: https://couponapi-service
          - name: ConnectionStrings__ProductConnectionString
            value: Server=.\\SQLEXPRESS;Database=InfyShoppingCartAPI;Trusted_Connection=True;MultipleActiveResultSets=true

---

apiVersion: v1
kind: Service
metadata:
  name: shoppingcartapi-service
spec:
  type: NodePort
  selector:
    app: shoppingcartapi
  ports:
    - port: 80